version: "3.9" #version of docker-compose
services:
  db:
    image: "postgres:13.4-alpine"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=diploma
    ports:
      - "35433:5432"
