spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:35433/diploma
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    user: root
    password: root
    url: jdbc:postgresql://localhost:35433/diploma
    connect-retries: 3
    mixed: true
    locations: classpath:db/migration
