spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:35433/diploma
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
