create table users
(
    id          int8 generated by default as identity,
    createdAt   timestamp not null ,
    email       varchar(255) not null ,
    firstName   varchar(255) not null ,
    lastName    varchar(255),
    location    varchar(255),
    nationality varchar(255) not null ,
    password    varchar(255) not null ,
    primary key (id)
);

insert into users (createdAt, email, firstName, lastName, location, nationality, password) VALUES
    ('2022-12-04 21:51:14.000000', 'email@gmail.com', 'First', 'Last', 'Minsk', 'Belarus', 'password');